# Generated by Django 5.1.1 on 2024-11-06 08:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('typeofadd', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contactemail', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'contact_table',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'Customer_table',
            },
        ),
        migrations.CreateModel(
            name='Foodcourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='No Image', upload_to='')),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('description', models.TextField(max_length=100)),
                ('categoty', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'food_details',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, default='No Image', upload_to='')),
                ('address', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'merchant_table',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ndate_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mail', models.EmailField(max_length=254)),
                ('quantity', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('address', models.TextField()),
                ('odatetime', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 6, 14, 7, 3, 941852))),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.CharField(max_length=100)),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('finalcost', models.BigIntegerField()),
                ('stutuss', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.foodcourt')),
            ],
            options={
                'db_table': 'booking_food',
            },
        ),
        migrations.AddField(
            model_name='foodcourt',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.merchant'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('star', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.merchant')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('vmail', models.EmailField(max_length=254)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.foodcourt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.order')),
            ],
        ),
    ]
