# Generated by Django 5.1.6 on 2025-02-21 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 21, 15, 7, 48, 788645)),
        ),
    ]
