# Generated by Django 5.1.6 on 2025-02-27 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0002_alter_order_odatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='status',
            field=models.CharField(default='On Hold', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='odatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 27, 10, 10, 44, 640193)),
        ),
    ]
