# Generated by Django 5.1.6 on 2025-02-27 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0003_merchant_status_alter_order_odatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 27, 10, 47, 35, 759756)),
        ),
    ]
