# Generated by Django 5.2.3 on 2025-06-23 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0004_alter_order_odatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 23, 16, 56, 39, 53660)),
        ),
    ]
